// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ScramButton;
extern lv_obj_t * ui_PowerButton;
extern lv_obj_t * ui_ElectromagnetButton;
extern lv_obj_t * ui_SpeedSelectButton;
extern lv_obj_t * ui_ForwardButton;
extern lv_obj_t * ui_BackwardButton;
extern lv_obj_t * ui_ScramLabel;
extern lv_obj_t * ui_PowerLabel;
extern lv_obj_t * ui_ElectromagnetLabel;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_ForwardLabel;
extern lv_obj_t * ui_BackwardLabel;
extern lv_obj_t * ui_PositionSetArc;
extern lv_obj_t * ui_Rotaryknob1read;
extern lv_obj_t * ui_RotaryKnob2Read;
extern lv_obj_t * ui_PositionSetLabel;
extern lv_obj_t * ui_PositionReadLabel;
extern lv_obj_t * ui_RotaryKnob1;
extern lv_obj_t * ui_RotaryKnob2Label;
extern lv_obj_t * ui_PositionReadBar;
extern lv_obj_t * ui_PositionMaxCheckbox;
extern lv_obj_t * ui_PositionMinCheckbox;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScramButton;
extern lv_obj_t * uic_PowerButton;
extern lv_obj_t * uic_ElectromagnetButton;
extern lv_obj_t * uic_SpeedSelectButton;
extern lv_obj_t * uic_ForwardButton;
extern lv_obj_t * uic_BackwardButton;
extern lv_obj_t * uic_Scram;
extern lv_obj_t * uic_PowerLabel;
extern lv_obj_t * uic_ElectromagnetLabel;
extern lv_obj_t * uic_BackwardLabel;
extern lv_obj_t * uic_PositionSetLabel;
extern lv_obj_t * uic_PositionReadLabel;
extern lv_obj_t * uic_RotaryKnob1;
extern lv_obj_t * uic_RotaryKnob2Label;
extern lv_obj_t * uic_PositionReadBar;
extern lv_obj_t * uic_PositionMaxCheckbox;
extern lv_obj_t * uic_PositionMinCheckbox;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

