// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_PositionMinCheckbox;
lv_obj_t * uic_PositionMaxCheckbox;
lv_obj_t * uic_PositionReadBar;
lv_obj_t * uic_RotaryKnob2Label;
lv_obj_t * uic_RotaryKnob1;
lv_obj_t * uic_PositionReadLabel;
lv_obj_t * uic_PositionSetLabel;
lv_obj_t * uic_BackwardLabel;
lv_obj_t * uic_ElectromagnetLabel;
lv_obj_t * uic_PowerLabel;
lv_obj_t * uic_Scram;
lv_obj_t * uic_BackwardButton;
lv_obj_t * uic_ForwardButton;
lv_obj_t * uic_SpeedSelectButton;
lv_obj_t * uic_ElectromagnetButton;
lv_obj_t * uic_PowerButton;
lv_obj_t * uic_ScramButton;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ScramButton = NULL;
lv_obj_t * ui_PowerButton = NULL;
lv_obj_t * ui_ElectromagnetButton = NULL;
lv_obj_t * ui_SpeedSelectButton = NULL;
lv_obj_t * ui_ForwardButton = NULL;
lv_obj_t * ui_BackwardButton = NULL;
lv_obj_t * ui_ScramLabel = NULL;
lv_obj_t * ui_PowerLabel = NULL;
lv_obj_t * ui_ElectromagnetLabel = NULL;
lv_obj_t * ui_SpeedLabel = NULL;
lv_obj_t * ui_ForwardLabel = NULL;
lv_obj_t * ui_BackwardLabel = NULL;
lv_obj_t * ui_PositionSetArc = NULL;
lv_obj_t * ui_Rotaryknob1read = NULL;
lv_obj_t * ui_RotaryKnob2Read = NULL;
lv_obj_t * ui_PositionSetLabel = NULL;
lv_obj_t * ui_PositionReadLabel = NULL;
lv_obj_t * ui_RotaryKnob1 = NULL;
lv_obj_t * ui_RotaryKnob2Label = NULL;
lv_obj_t * ui_PositionReadBar = NULL;
lv_obj_t * ui_PositionMaxCheckbox = NULL;
lv_obj_t * ui_PositionMinCheckbox = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScramButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ScramButton, 100);
    lv_obj_set_height(ui_ScramButton, 50);
    lv_obj_set_x(ui_ScramButton, -316);
    lv_obj_set_y(ui_ScramButton, 174);
    lv_obj_set_align(ui_ScramButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScramButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScramButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_PowerButton, 100);
    lv_obj_set_height(ui_PowerButton, 50);
    lv_obj_set_x(ui_PowerButton, -188);
    lv_obj_set_y(ui_PowerButton, 175);
    lv_obj_set_align(ui_PowerButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PowerButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ElectromagnetButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ElectromagnetButton, 100);
    lv_obj_set_height(ui_ElectromagnetButton, 50);
    lv_obj_set_x(ui_ElectromagnetButton, -61);
    lv_obj_set_y(ui_ElectromagnetButton, 175);
    lv_obj_set_align(ui_ElectromagnetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ElectromagnetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ElectromagnetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpeedSelectButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedSelectButton, 100);
    lv_obj_set_height(ui_SpeedSelectButton, 50);
    lv_obj_set_x(ui_SpeedSelectButton, 61);
    lv_obj_set_y(ui_SpeedSelectButton, 174);
    lv_obj_set_align(ui_SpeedSelectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeedSelectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SpeedSelectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ForwardButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ForwardButton, 100);
    lv_obj_set_height(ui_ForwardButton, 50);
    lv_obj_set_x(ui_ForwardButton, 194);
    lv_obj_set_y(ui_ForwardButton, 175);
    lv_obj_set_align(ui_ForwardButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ForwardButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ForwardButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackwardButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_BackwardButton, 100);
    lv_obj_set_height(ui_BackwardButton, 50);
    lv_obj_set_x(ui_BackwardButton, 315);
    lv_obj_set_y(ui_BackwardButton, 176);
    lv_obj_set_align(ui_BackwardButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackwardButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackwardButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScramLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ScramLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScramLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScramLabel, -317);
    lv_obj_set_y(ui_ScramLabel, 175);
    lv_obj_set_align(ui_ScramLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScramLabel, "Scram");

    ui_PowerLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PowerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowerLabel, -189);
    lv_obj_set_y(ui_PowerLabel, 175);
    lv_obj_set_align(ui_PowerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerLabel, "Power");

    ui_ElectromagnetLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ElectromagnetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ElectromagnetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ElectromagnetLabel, -61);
    lv_obj_set_y(ui_ElectromagnetLabel, 175);
    lv_obj_set_align(ui_ElectromagnetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ElectromagnetLabel, "Electromag");

    ui_SpeedLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel, 59);
    lv_obj_set_y(ui_SpeedLabel, 175);
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel, "Speed\nSelect");

    ui_ForwardLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ForwardLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ForwardLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ForwardLabel, 192);
    lv_obj_set_y(ui_ForwardLabel, 171);
    lv_obj_set_align(ui_ForwardLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ForwardLabel, "Forward");

    ui_BackwardLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BackwardLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackwardLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackwardLabel, 313);
    lv_obj_set_y(ui_BackwardLabel, 174);
    lv_obj_set_align(ui_BackwardLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackwardLabel, "Backward");

    ui_PositionSetArc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_PositionSetArc, 150);
    lv_obj_set_height(ui_PositionSetArc, 150);
    lv_obj_set_x(ui_PositionSetArc, -279);
    lv_obj_set_y(ui_PositionSetArc, -137);
    lv_obj_set_align(ui_PositionSetArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_PositionSetArc, 50);

    ui_Rotaryknob1read = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Rotaryknob1read, 150);
    lv_obj_set_height(ui_Rotaryknob1read, 150);
    lv_obj_set_x(ui_Rotaryknob1read, 68);
    lv_obj_set_y(ui_Rotaryknob1read, -143);
    lv_obj_set_align(ui_Rotaryknob1read, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Rotaryknob1read, 50);

    ui_RotaryKnob2Read = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_RotaryKnob2Read, 150);
    lv_obj_set_height(ui_RotaryKnob2Read, 150);
    lv_obj_set_x(ui_RotaryKnob2Read, 241);
    lv_obj_set_y(ui_RotaryKnob2Read, -150);
    lv_obj_set_align(ui_RotaryKnob2Read, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_RotaryKnob2Read, 50);

    ui_PositionSetLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PositionSetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PositionSetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositionSetLabel, -282);
    lv_obj_set_y(ui_PositionSetLabel, -51);
    lv_obj_set_align(ui_PositionSetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PositionSetLabel, "Position\n    Set");

    ui_PositionReadLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PositionReadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PositionReadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositionReadLabel, -312);
    lv_obj_set_y(ui_PositionReadLabel, -22);
    lv_obj_set_align(ui_PositionReadLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PositionReadLabel, "Position Read");

    ui_RotaryKnob1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RotaryKnob1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RotaryKnob1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RotaryKnob1, 68);
    lv_obj_set_y(ui_RotaryKnob1, -50);
    lv_obj_set_align(ui_RotaryKnob1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RotaryKnob1, "RotaryKnob\n          #1");

    ui_RotaryKnob2Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RotaryKnob2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RotaryKnob2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RotaryKnob2Label, 241);
    lv_obj_set_y(ui_RotaryKnob2Label, -53);
    lv_obj_set_align(ui_RotaryKnob2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RotaryKnob2Label, "RotaryKnob\n         #2");

    ui_PositionReadBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_PositionReadBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_PositionReadBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PositionReadBar, 663);
    lv_obj_set_height(ui_PositionReadBar, 10);
    lv_obj_set_x(ui_PositionReadBar, -9);
    lv_obj_set_y(ui_PositionReadBar, -1);
    lv_obj_set_align(ui_PositionReadBar, LV_ALIGN_CENTER);

    ui_PositionMaxCheckbox = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_PositionMaxCheckbox, "PositionMax");
    lv_obj_set_width(ui_PositionMaxCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PositionMaxCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositionMaxCheckbox, -291);
    lv_obj_set_y(ui_PositionMaxCheckbox, 35);
    lv_obj_set_align(ui_PositionMaxCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PositionMaxCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PositionMinCheckbox = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_PositionMinCheckbox, "PositionMin");
    lv_obj_set_width(ui_PositionMinCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PositionMinCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositionMinCheckbox, -292);
    lv_obj_set_y(ui_PositionMinCheckbox, 65);
    lv_obj_set_align(ui_PositionMinCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PositionMinCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    uic_ScramButton = ui_ScramButton;
    uic_PowerButton = ui_PowerButton;
    uic_ElectromagnetButton = ui_ElectromagnetButton;
    uic_SpeedSelectButton = ui_SpeedSelectButton;
    uic_ForwardButton = ui_ForwardButton;
    uic_BackwardButton = ui_BackwardButton;
    uic_Scram = ui_ScramLabel;
    uic_PowerLabel = ui_PowerLabel;
    uic_ElectromagnetLabel = ui_ElectromagnetLabel;
    uic_BackwardLabel = ui_BackwardLabel;
    uic_PositionSetLabel = ui_PositionSetLabel;
    uic_PositionReadLabel = ui_PositionReadLabel;
    uic_RotaryKnob1 = ui_RotaryKnob1;
    uic_RotaryKnob2Label = ui_RotaryKnob2Label;
    uic_PositionReadBar = ui_PositionReadBar;
    uic_PositionMaxCheckbox = ui_PositionMaxCheckbox;
    uic_PositionMinCheckbox = ui_PositionMinCheckbox;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_ScramButton = NULL;
    ui_ScramButton = NULL;
    uic_PowerButton = NULL;
    ui_PowerButton = NULL;
    uic_ElectromagnetButton = NULL;
    ui_ElectromagnetButton = NULL;
    uic_SpeedSelectButton = NULL;
    ui_SpeedSelectButton = NULL;
    uic_ForwardButton = NULL;
    ui_ForwardButton = NULL;
    uic_BackwardButton = NULL;
    ui_BackwardButton = NULL;
    uic_Scram = NULL;
    ui_ScramLabel = NULL;
    uic_PowerLabel = NULL;
    ui_PowerLabel = NULL;
    uic_ElectromagnetLabel = NULL;
    ui_ElectromagnetLabel = NULL;
    ui_SpeedLabel = NULL;
    ui_ForwardLabel = NULL;
    uic_BackwardLabel = NULL;
    ui_BackwardLabel = NULL;
    ui_PositionSetArc = NULL;
    ui_Rotaryknob1read = NULL;
    ui_RotaryKnob2Read = NULL;
    uic_PositionSetLabel = NULL;
    ui_PositionSetLabel = NULL;
    uic_PositionReadLabel = NULL;
    ui_PositionReadLabel = NULL;
    uic_RotaryKnob1 = NULL;
    ui_RotaryKnob1 = NULL;
    uic_RotaryKnob2Label = NULL;
    ui_RotaryKnob2Label = NULL;
    uic_PositionReadBar = NULL;
    ui_PositionReadBar = NULL;
    uic_PositionMaxCheckbox = NULL;
    ui_PositionMaxCheckbox = NULL;
    uic_PositionMinCheckbox = NULL;
    ui_PositionMinCheckbox = NULL;

}
